# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Collect files for dependencies cache key
          command: |
            find . -path ./examples -prune -o -name '*.gradle*' -type f -print0 \
            | sort -z \
            | xargs -0 cat \
            > /tmp/circleci_cache_key
      - restore_cache:
          name: Restore dependencies cache
          keys:
            - v2-dependencies-{{ checksum "/tmp/circleci_cache_key" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: ./gradlew build

      - restore_cache:
          name: Restore protobuf cache
          keys:
            - v3-protobuf-3.10.1

      - run:
          name: Build protoc and protobuf conformance-test-runner
          command: |
            cd ~
            if [ -e ./protobuf/install/bin/protoc -a -e ./protobuf/conformance/conformance-test-runner ]; then
              exit
            fi
            curl -sSLO https://github.com/protocolbuffers/protobuf/releases/download/v3.10.1/protobuf-all-3.10.1.tar.gz
            tar xzvf protobuf-all-3.10.1.tar.gz
            mv protobuf-3.10.1 protobuf
            cd protobuf
            ./configure --prefix="$(pwd)/install"
            make
            make install
            cd conformance
            make

      - save_cache:
          name: Save protobuf cache
          paths:
            - ~/protobuf
          key: v3-protobuf-3.10.1

      - run:
          name: Ensure bundled types are up-to-date
          command: |
            export PATH="$PATH:$HOME/protobuf/install/bin"
            # need to stop the gradle daemon from the earlier step so it can pick up the new PATH value
            ./gradlew --stop
            ./gradlew -Dprotoc.path=$HOME/protobuf/install \
              :runtime:generateWellKnownTypes \
              :protoc-gen-kotlin-lib:generateProto \
              :runtime:generateTestTypes \
              :conformance-lib:generateProto
            if [ -n "$(git status --porcelain)" ]; then
              echo "*** Found uncommitted changes to bundled types: ***"
              git status
              exit 1
            else
              exit 0
            fi

      - run:
          name: Run conformance tests
          command: |
            export CONF_TEST_PATH=~/protobuf/conformance/conformance-test-runner
            ./gradlew :conformance:installDist
            ./conformance-lib/test-conformance.sh

      - save_cache:
          name: Save dependencies cache
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "/tmp/circleci_cache_key" }}
          when: always
